### PR TITLE
Refactoring, dead code elimination and BSS extraction 

### PR DESCRIPTION
**Pull request by 0xABADCAFE**
Ongoing refactoring of identifier names, dead code elimination, etc.
Moving zero-initialised data blocks and globals to a common BSS segment.
Various optimisations, esp. replacing of integer division by immediate.

Compiled with main
```
code(acrx128):      368132 bytes
bss(aurw16):        150958 bytes
data(adrw1):         87552 bytes
bss_c(aurw256):     128192 bytes
data_c(adrw2):       58362 bytes

executable: 922760 bytes
```

This branch
```
bss(aurw16):	      210010 bytes
code(acrx128):	      299312 bytes
data(adrw1):	       87552 bytes
bss_c(aurw256):	      128192 bytes
data_c(adrw2):	       58362 bytes


executable: 848164 bytes
```

### CODE REVIEW

**Comment by 0xABADCAFE** [comment]
Marking as ready for review before it gets any bigger!

**Comment by mheyer32** [comment]
I'm ok with the changes. But could you please keep functional changes separate from purely renaming ones?
This will help in future in case we have to do some source archeology or need to bisect regressions.

**Comment by 0xABADCAFE** [comment]
The BSS extraction and renaming were part of the same work, but they aren't
functional changes in my view. I can put the small optimisations into
another branch.

**Comment by mheyer32** [comment]
> I can put the small optimisations into another branch.
Yes, thats what I'm referring to.

**Comment by 0xABADCAFE** [comment]
Phew. I thought you meant the extraction too, lol

**Comment by 0xABADCAFE** [comment]
> > I can put the small optimisations into another branch.
> > Yes, thats what I'm referring to.

Are you OK if I revert those optimisations by just changing the commenting then raising a second PR afterwards to to put them back? It seems like it will be less work and will still guarantee the same separation in the end squashed commit history.

**Comment by 0xABADCAFE** [comment]
> > I can put the small optimisations into another branch.
> > Yes, thats what I'm referring to.

That's now done. The original arithmetic is reinstated and ready to be replaced again in a subsequent PR.

Perhaps that's the best way to do this, as alternating style/nonfunctional then fixes, on a regular cycle.

If you are OK, it would be nice to get this squashed and merged.

**Pull request merged**
