### PR TITLE
Maintenance/cleanup

### PR DESCRIPTION
**Pull request by 0xABADCAFE**
Work in progress
- Defining entity member fields (objects, enemies, player)
- Renaming for clarity where appropriate

### CODE REVIEW

**Comment by mheyer32** [comment]
I know, this will be a lot more work, but could this be a chance to switch over to the STRUCT syntax for what is essentially structs?
The advantage is that the struct definitions will now also contain a 'type' information (as opposed 'just' being a suffix).

**Comment by 0xABADCAFE** [comment]
Funny you should say that but i was thinking the same thing by the time I
pushed.

**Comment by 0xABADCAFE** [comment]
Based on the conventions we'd previously talked about, I have adopted the following for "custom type" definitions:

- Structure name: `<module>_<typename>T`
- Member names: `<module>_<typename>T_<member name>_<size>`

The size is included since this is now what drives the offset position. Example:
```
	; AI Entity Type
	STRUCTURE AI_EntT, 18 ; definitions begin at offset 18...
		UBYTE AI_EntT_NumLives_b
		UBYTE AI_EntT_DamageTaken_b
		UBYTE AI_EntT_CurrentMode_b
		UBYTE AI_EntT_TeamNumber_b       
	; ...
```

**Comment by 0xABADCAFE** [comment]
Dont merge this!
The last update from main has introduced some horrible crashy mess that only affects this branch,

**Comment by 0xABADCAFE** [comment]
I am going to close this PR down. I will redo the initial work in a clean branch from main as it's not really obvious what has broken.

**Pull request closed without merging**
