### PR TITLE
Maintenance/bss and data extraction

### PR DESCRIPTION
**Pull request by 0xABADCAFE**
- More zero-initialised data extracted to BSS 
- Added DATA section for initialised global data and extracted out various initialised data by area of concern.

```
bss(aurw16):	      241412 bytes
data(adrw16):	      144098 bytes
code(acrx128):	      210648 bytes
bss_c(aurw256):	      128416 bytes
data_c(adrw2):	       58362 bytes

Executable size: 814740 bytes
```

### CODE REVIEW

**Comment by mheyer32** [comment]
Overall, LGTM.
One thing to keep in mind: when moving data out of the code segment into bss, the assembler looses the ability to use PC-relative addressing for these variables. This might affect some performance critical paths - but I can't quantify it.

**Comment by 0xABADCAFE** [comment]
I did look into that and found that on 060 it seems like PC relative
addressing takes longer than a resolved address. I haven't replaced those
in more inner loops, as you will see in the wall rendering code.

**Comment by mheyer32** [comment]
Awesome! Thanks for being so thorough!

**Comment by 0xABADCAFE** [comment]
We can consider some of those inner loops but I'd rather get some benchmarks before changing them. The innermost ones I left use label(pc, dX*N) addressing modes which would take more instructions to implement using a regular address register so the EA overhead of the PC is likely less.

**Comment by 0xABADCAFE** [comment]
Time to mosh and squirge...

**Pull request merged**
