### PR TITLE
manual merge of my changes to current

### PR DESCRIPTION
**Pull request by AndyLoft**
manual merge after making a mess of my main, works for me. feel free to reject the changes I have made as I feel they will become out of date quickly with the progress yourself and karlos are making, but, while simple, may offer ideas worth implementing.

### CODE REVIEW

**Comment by AndyLoft** [comment]
the main change is around the lighting animation, the others are just things I wanted to have. the FPS counter works but seems to be either over drawn in the current double buffered version when in full screen. opening in full screen if an 040 or better would not be required if there were a prefs file for game settings. most what I have added could be done better I am sure.

**Comment by mheyer32** [comment]
We should split this up into multiple smaller, functionally atomic commits.
`git commit --amend`
allows not only to add things to a single commit after it had been committed, but also take out changes. This is a way to split the initial big commit into smaller ones.
'git rebase -i ' allows interactive rebase to reorder commits, squash them, change commit messages etc. Super useful tool.
once you have done that,
'git push -f'
allows to force-push to your remote branch 'merge-ATM-pipper' again (even though you may have changed history). GitHub will reflect this MR with the new commits in your branch.

**Comment by AndyLoft** [comment]
agreed, I will give it a go, but, may take some time.

**Comment by AndyLoft** [comment]
err. I think I did it correct.

**Comment by 0xABADCAFE** [comment]
I think we should aim to merge these changes.

**Comment by 0xABADCAFE** [comment]
Deconflicted the changeset based on the conversation at EAB.

**Pull request merged**
