### PR TITLE
Fix C version of Sys_ReadMouse

### PR DESCRIPTION
**Pull request by mras0**
Hopefully accurate replacement of the vertical mouse movement. Code is a bit weird and could perhaps be improved, but it's not performance critical.

(Note: I don't think the "ELSE IFND" construct worked in vasm).

### CODE REVIEW

**Comment by mheyer32** [comment]
LGTM

**Review by 0xABADCAFE — APPROVED** [review]

**Comment by 0xABADCAFE** [comment]
Just going to test it and if it's good I'll merge.

**Comment by 0xABADCAFE** [comment]
Works on my machine (TM)

**Comment by 0xABADCAFE** [comment]
Damn shame about the conditional in vasm. Strange it has no errors.

**Pull request merged**
