### PR TITLE
Cleanup - Code Modularisation Part 1

### PR DESCRIPTION
**Pull request by 0xABADCAFE**
Code specific to the following areas of responsibility have been moved to their own files:
- AI -> modules/ai.s
- File IO -> modules/file_io.s
- Resource Management -> modules/res.s

The individual steps (commit each) were:
- Apply the new coding style guides to code identified in each area
- Move files to the new location (renaming based on content, e.g. newloadfromdisk.s -> modules/file_io.s)
- Disentangle code in the moved files based on responsibility.

### CODE REVIEW

**Comment by mheyer32** [comment]
I wouldn't have gone as far as moving the modules to their own directory... its not that large of a project and you'd end up with one main file in the project directory, while everything else stays in the module directory... so not much gain. 
But I don't object to it overly. If its more convenient to you to leave it the way you've done, I'm ok with that.
I appreciate your work!

**Comment by 0xABADCAFE** [comment]
The reason for the subdirectory was just to be able to keep the refactored code visibly separate from what's still left to do. If or all ends up in the modules directory or means phase 1 is done. After this point should be possible to begin the xdef/xref rework.

**Comment by 0xABADCAFE** [comment]
I wonder how many different things will fall out of the hires.s file too. It's a bit or a chonker.

**Comment by nvmheyer** [comment]
yeah, hires.s is a mixed bag of floor rendering, map point rotation, map rendering, sound rendering, music playback... Not sure whats left after it.

**Comment by mheyer32** [comment]
yeah, hires.s is a mixed bag of floor rendering, map point rotation, map rendering, sound rendering, music playback... Not sure whats left after it.

**Comment by 0xABADCAFE** [comment]
Something else I forgot to add in the description - as the files are teased apart I am also teasing apart the data and code references too. The idea is that there's a lot of zero initialised data that we may well be able to move to the .bss section

**Comment by 0xABADCAFE** [comment]
Am I ok to merge this or do you want to change the layout? I don't mind having the new files in the same directory, it was just a visual aid.

**Pull request merged**
